import localFont from "next/font/local";
import "./globals.css";
import Nav from "./components/Nav";
import { GoogleAdSense } from "./components/Ads";
import { Provider } from "./components/Provider";
import { Metadata } from "next";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "cats story world",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased select-none`}
      >
            <Nav />
            <Provider>
              {children}
            </Provider>
            <GoogleAdSense />
      </body>
    </html>

  );
}
